#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JAWA.Resource", IsApplication=true)]

namespace JAWA
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int card_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int weathericons_0000_01 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int weathericons_0001_02 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int weathericons_0002_03 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int weathericons_0003_04 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int weathericons_0004_05 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int weathericons_0005_06 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int weathericons_0006_07 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int weathericons_0007_08 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int weathericons_0008_09 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int weathericons_0009_10 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int weathericons_0010_11 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int weathericons_0011_12 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int weathericons_0012_13 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int weathericons_0013_14 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int weathericons_0014_15 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int weathericons_0015_16 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int weathericons_0016_17 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int weathericons_0017_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int weathericons_0018_19 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int weathericons_0019_20 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int weathericons_0020_21 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int weathericons_0021_22 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int weathericons_0022_23 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int weathericons_0023_24 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int weathericons_0024_25 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int weathericons_0025_26 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int weathericons_0026_27 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int weathericons_0027_28 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int weathericons_0028_29 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int weathericons_0029_30 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int weathericons_0030_31 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int weathericons_0031_32 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int weathericons_0032_33 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int weathericons_0033_34 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int weathericons_0034_35 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int weathericons_0035_36 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int weathericons_0036_37 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int weathericons_0037_38 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int weathericons_0038_39 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int weathericons_0039_40 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int weathericons_0040_41 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int weathericons_0041_42 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int weathericons_0042_43 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int weathericons_0043_44 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int weathericons_0044_45 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int weathericons_0045_46 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int weathericons_0046_47 = 2130837553;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int EditText01 = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout01 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ListView01 = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int action_search = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int city_name = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int country = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int listview = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int metadata = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int temperature = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int weather_icon = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_search = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int header_bg = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_weather = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int main_activity_option_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int action_settings = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int search_hint = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int search_label = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int temperature_in_celcius = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int TextAppearance_Large = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int TextAppearance_Large_Light = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
